# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_control', '0002_room_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='power',
            field=models.FloatField(default=0.0, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='service',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='work',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(default=1.0, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='speed',
            field=models.CharField(default='low', max_length=11, null=True),
        ),
    ]
