# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160607_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='mode',
        ),
        migrations.AddField(
            model_name='server',
            name='mode',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
