# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_server_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costperday',
            old_name='power',
            new_name='day_power',
        ),
    ]
