# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160608_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='costperday',
            name='room_id',
            field=models.IntegerField(db_index=True, default=1, null=True, unique=True),
        ),
    ]
