# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_costperday_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costperday',
            name='create_time',
            field=models.DateField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='costperday',
            name='room_id',
            field=models.IntegerField(db_index=True, default=1, null=True),
        ),
    ]
