# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160609_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='speed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
