# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_identity', models.CharField(default='', max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_profile',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, default=1, null=True, unique=True)),
                ('numbers', models.CharField(default=0, max_length=8, null=True, unique=True)),
                ('speed', models.IntegerField(default=1, null=True)),
                ('price', models.FloatField(default=0.0, max_length=8, null=True)),
                ('total_cost', models.FloatField(default=0.0, max_length=8, null=True)),
                ('room_temperature', models.FloatField(default=20.0, max_length=8, null=True)),
                ('setting_temperature', models.FloatField(default=20.0, max_length=8, null=True)),
                ('host', models.CharField(db_index=True, default='127.0.0.1:8000', max_length=32, null=True)),
                ('ip_address', models.CharField(default='', max_length=32, null=True)),
                ('mode', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'room_info',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, default=1, null=True, unique=True)),
                ('host', models.CharField(default='127.0.0.1:8000', max_length=32, null=True)),
            ],
            options={
                'db_table': 'server_info',
            },
        ),
    ]
