# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='link',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
