# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.AlterField(
            model_name='room',
            name='speed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
